### ISSUE TITLE
Missing notes received date into indexed data

### ISSUE THREAD

**Issue by titioft** [pierrephi/notes-quicklook-plugin#1]
Hi Pierrephi,

I have been using your plugin for notes quicklook. However, it is missing an important field which is the date of reception of the notes mail. The index is listed in the right order but as I have several years of mails it is difficult to see at first look which one is from which year. Looking at your code I don't see the date field anywhere. Is it something that exist in the output of the spotlight search within notes?

Thanks in advance,

-Olivier

**Comment by pierrephi** [comment]
Hi Olivier

My company has migrated out of lotus notes (finally) and I unfortunately no longer have access to a lotus notes mail DB to check this out and update the repo. If you do find how to do this I will be happy to accept a pull request though
